### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by binarykitchen** [zauni/node-pngquant-bin#1]
Guys, I have this issue related to your package. I cannot install it on my Mac OS X. Any clues?

```
> pngquant-bin@0.1.5 postinstall /Users/mick/projects/signdna/node_modules/grunt-contrib-imagemin/node_modules/pngquant-bin
> node lib/check.js


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/Users/mick/projects/signdna/node_modules/grunt-contrib-imagemin/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/mout/object'
npm ERR! error rolling back  grunt-contrib-imagemin@0.4.0 { [Error: ENOTEMPTY, rmdir '/Users/mick/projects/signdna/node_modules/grunt-contrib-imagemin/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/mout/object']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/Users/mick/projects/signdna/node_modules/grunt-contrib-imagemin/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/mout/object' }
npm ERR! pngquant-bin@0.1.5 postinstall: `node lib/check.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the pngquant-bin@0.1.5 postinstall script.
npm ERR! This is most likely a problem with the pngquant-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/check.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls pngquant-bin
npm ERR! There is likely additional logging output above.
```

**Comment by optyler** [comment]
Hi, I got the same issue, can you tell us how did you resolve it?
